title: Anurag Mishra
email: am2552@g.rit.edu
description: >- # this means to ignore newlines until "baseurl:"
  Personal website of Anurag Mishra - MS in AI student at RIT, 
  researching Machine Learning and Natural Language Processing.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://i-anuragmishra.github.io"
github_username: i-anuragmishra
linkedin_username: i-anuragmishra

# Build settings
markdown: kramdown
remote_theme: academicpages/academicpages.github.io@gh-pages
repository: i-anuragmishra/i-anuragmishra.github.io

# Site Author
author:
  name: "Anurag Mishra"
  avatar: "profile.png"
  bio: "MS in AI student at RIT | Machine Learning & NLP Researcher"
  location: "Rochester, NY"
  employer: "Rochester Institute of Technology"
  googlescholar: 
  email: "am2552@g.rit.edu"
  researchgate:
  uri:
  bitbucket:
  codepen:
  dribbble:
  flickr:
  facebook:
  foursquare:
  github: "i-anuragmishra"
  google_plus:
  keybase:
  instagram:
  lastfm:
  linkedin: "i-anuragmishra"
  orcid: 
  pinterest:
  soundcloud:
  stackoverflow:
  steam:
  tumblr:
  twitter: 
  vine:
  weibo:
  xing:
  youtube:

# Site Settings
locale: "en-US"
title_separator: "-"
name: &name "Anurag Mishra"
breadcrumbs: false
words_per_minute: 160

# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - config
  - gulpfile.js
  - log
  - node_modules
  - package.json
  - tmp
  - vendor
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Collections
collections:
  teaching:
    output: true
    permalink: /:collection/:path/
  publications:
    output: true
    permalink: /:collection/:path/
  portfolio:
    output: true
    permalink: /:collection/:path/
  talks:
    output: true
    permalink: /:collection/:path/

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  # _teaching
  - scope:
      path: ""
      type: teaching
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
  # _publications
  - scope:
      path: ""
      type: publications
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
  # _portfolio
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: true
      share: true
      comment: true
  # _talks
  - scope:
      path: ""
      type: talks
    values:
      layout: talk
      author_profile: true
      share: true

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-remote-theme
# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji 