title: Anurag Mishra
email: your-email@domain.com
description: >- # this means to ignore newlines until "baseurl:"
  Personal website of Anurag Mishra
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://i-anuragmishra.github.io" # the base hostname & protocol for your site
twitter_username: your-twitter-handle
github_username: i-anuragmishra

# Build settings
markdown: kramdown
remote_theme: academicpages/academicpages.github.io
permalink: pretty

# Site Author
author:
  name: "Anurag Mishra"
  avatar: "profile.png"
  bio: "Your bio here"
  location: "Your Location"
  employer: 
  googlescholar: 
  email: 
  researchgate:
  uri:
  bitbucket:
  codepen:
  dribbble:
  flickr:
  facebook:
  foursquare:
  github: "i-anuragmishra"
  google_plus:
  keybase:
  instagram:
  lastfm:
  linkedin:
  orcid: 
  pinterest:
  soundcloud:
  stackoverflow:
  steam:
  tumblr:
  twitter: 
  vine:
  weibo:
  xing:
  youtube:

# Site Settings
locale: "en-US"
title_separator: "-"
name: &name "Anurag Mishra"
breadcrumbs: false
words_per_minute: 160

# Collections
collections:
  teaching:
    output: true
    permalink: /:collection/:path/
  publications:
    output: true
    permalink: /:collection/:path/
  portfolio:
    output: true
    permalink: /:collection/:path/
  talks:
    output: true
    permalink: /:collection/:path/ 